<h1>Lista de BD Mongo</h1>

<a 	class="btn btn-success" 
	title="Novo" 
	href="<?php echo $this->url('clientes',
    							array(	'controller' => 'ClientesController',
										'action'=>'add'
    								)); ?>">
    <span class="glyphicon glyphicon-plus"></span>
 </a>
<table class="table table-striped table-bordered table-hover">
		<thead>
		    <tr>
		        <th>Id</th>
		        <th>Nome</th>
		        <th>Email</th>
		        <th>Telefone</th>
		        <th>Setor</th>
		    </tr>
	    </thead>
	    <tbody>

	<?php foreach($this->home as $doc): ?>
		<tr>
			<td><?php echo $this->escapeHtml($doc->getId()); ?></td>			
			<td><?php echo $this->escapeHtml($doc->getNome()); ?></td>			
			<td><?php echo $this->escapeHtml($doc->getEmail()); ?></td>			
			<td><?php echo $this->escapeHtml($doc->getTelefone()); ?></td>			
			<td><?php echo $this->escapeHtml($doc->getSetor()); ?></td>
		
		</tr>
	<?php endforeach;?>
		</tbody>
	</table>	